# fly.toml app configuration file generated for lonely-cat on 2025-08-01T16:31:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lonely-cat'
primary_region = 'ord'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  cpu_kind = 'shared'
